### ISSUE TITLE
bug: static site not building correctly

### ISSUE THREAD

**Issue by conorsch** [penumbra-zone/guide#8]
Since converting from mdbook to nextra, I've encountered a problem: I can browse all of the docs on https://guide.penumbra.zone, as long as I use the links in the nav bar. If I then refresh the page, however, I get a 404. 

Indeed, even navigating directly to specific URLs in a fresh tab shows a 404. Here's a terminal session illustrating the same:

```
❯ curl -sI https://guide.penumbra.zone | rg ^HTTP
HTTP/2 200

❯ curl -sI https://guide.penumbra.zone/web | rg ^HTTP
HTTP/2 404
```

Notably I cannot reproduce this using `pnpm dev` locally, which runs a livereload environment. However, I can indeed reproduce it if I instead build the serve the static docroot:

```
rm -rf ./out
pnpm install
pnpm build
python3 -m http.server --directory ./out
```

Perhaps I'm misunderstanding what `pnpm build` does: I expected it to reproduce a truly static docroot, but the behavior I'm seeing is weirdly SPA-ish. Maybe there's something we should be doing with `_meta.json` files to ensure the subpage routes work?

**Comment by VanishMax** [comment]
@conorsch I tried using your example with `python3 -m http.server --directory ./out`, and it turns out that, for example, `/dex` route returns 404 but `/dex.html` works correctly. I found that the `cleanUrls` flag in Firebase might help with that: https://firebase.google.com/docs/hosting/full-config#control_html_extensions

**Comment by conorsch** [comment]
That's very helpful. I've added `cleanUrls: true` in #12, and post-deploy, that seems to have addressed the issue. I'm not stoked about needing to perform that type of URL rewriting at the hosting layer, though: I'd prefer that the `pnpm build` process emit a fully functional and truly static docroot, suitable for direct serving via a simple HTTP server. Even after poring over the nextra docs, I can't find the right knob to twiddle. But we all have piles of work to do, so I'm going to call this one done. 

Thanks for the help, @VanishMax!
